### ISSUE TITLE
SCons error when building addon

### ISSUE THREAD

**Issue by ScottChesworth** [GerardKessler/whatsapp#3]
There's a small mistake that I need to fix in the English translation. I'm setting up a new git environment here so I can make the correction then send you a pull request instead of attaching files. But, SCons throws this error when I try to build locally for testing.

'msgfmt' is not recognized as an internal or external command, operable program or batch file.
scons: *** [addon\locale\en\LC_MESSAGES\nvda.mo] Error 1
scons: building terminated because of errors.

I have python-gettext installed, thought that included msgfmt, but I guess not. Do you have any idea of where I'm going wrong here?

Thanks in advance for any advice.

**Comment by ghost** [comment]
Hi Scott. I don't know if I understood the problem correctly, but I think that this error occurs when the path of the bin folder needs to be added to the environment variables. For example: "C:\Program Files (x86)\Poedit\GettextTools\bin"

**Comment by ScottChesworth** [comment]
Apologies for the slow response, only just had some spare time to try fixing this. Your suggestion was perfect, thanks man!
