### ISSUE TITLE
Unable to submit PR with English translation updates

### ISSUE THREAD

**Issue by ScottChesworth** [GerardKessler/whatsapp#4]
Uh oh, it's me again. :)

I've made some improvements to the English translation. Unfortunately when I try to make a pull request using "git push origin englishTranslation" (englishTranslation is my branch name), git gives me this error:
"ERROR: Permission to GerardKessler/whatsapp.git denied to ScottChesworth. Please make sure you have the correct access rights and the repository exists."

well, I'm 100% sure the repository exists, because I cloned from it. So, how do I get access rights to send you these improvements?

Thanks in advance for any advice.

**Comment by ghost** [comment]
Hi Scott. Unfortunately you are talking to someone who is pretty inept at git. I remember doing something to the plugin folder when I got an error that I couldn't fix. Perhaps in that change that branch was modified. I do not know. My apologies for that. If you want, send me the translated files and I'll add them to the repository without any problems.
