### ISSUE TITLE
Can you add the "Texto del mensaje" report new in V1.4 to translation strings?

### ISSUE THREAD

**Issue by ScottChesworth** [GerardKessler/whatsapp#5]
I'm not seeing a line to translate this string in the po file. Can you add that, or should I translate it somewhere else in the repo?

**Comment by ghost** [comment]
Hola. Creo que había un error en el archivo po en inglés. La cadena texto del mensaje estaba traducida como cancelar mensaje. Ya lo he corregido. También figuraba una cadena con tan solo un signo  (:)
