### ISSUE TITLE
Can you add English translation of ReadMe?

### ISSUE THREAD

**Issue by ScottChesworth** [GerardKessler/whatsapp#6]
I've received some requests for an English translation of the documentation. Pasting it here in markdown format as a comment, unfortunately I still can't figure out why GitHub won't accept pull requests to this repo. Hope you can use it!

# WhatsApp
Author: [Gerardo Kessler](http://gera.ar)
Important:
This add-on is only compatible with the UWP version of WhatsApp, currently known as WhatsApp Beta. If you have other add-ons that are activated with other versions of the app such as WhatsApp-desktop, those must be disabled to avoid conflicts.
This add-on provides keyboard shortcuts for important functions of the application, as well as the renaming of unlabeled objects.

## Command List:
* Open the application; unassigned by default, choose which keystroke to use in NVDA/Preferences/Input Gestures
* Record and send voice message; control + r
* Discard voice message during recording; control + shift + r
* Speak the time elapsed during recording; control + t
* Move focus between message list and edit box; alt + left arrow
* Focus the chats list; alt + right arrow
* Speak the name of the active conversation with contact or group; control + shift + t
* Display selected message in a window (useful to skip hearing quoted content); alt + r
* Press the Attach button; control + shift + a
* Press the Audio call button; control + shift + l
* Press the Video call button; control + shift + v
* Press the Chat info button; control + shift + i
* Press the Options button; control + shift + o
* Press the New chat button; control + shift + n
* Toggle edited posts (if enabled, phone numbers of people who aren't in your contacts will be stripped when reading the message list); control + shift + e
* Focus start of unread messages; alt + down arrow

## App Shortcuts (these are native shortcuts provided by WhatsApp):
* Chat search box; control + f
* Message search box; control + shift + f
* Next chat; control + tab
* Previous chat; control + shift + tab

## Translations:

The following people contributed translations of this add-on

* Remy Ruiz (French)
* Umut KORKMAZ (Turkish)
* Valentin Kupriyanov (Russian)
*  Scott Chesworth (English)

**Comment by ghost** [comment]
Muchas gracias Scott. Ya he subido el repositorio con los cambios, y he actualizado el archivo de la última release.

**Comment by ScottChesworth** [comment]
Weird, I'm not seeing the English version on the landing page yet.

**Comment by ghost** [comment]
El archivo readme estaba ignorado en el .gitignore, no sé por qué. Ya lo he quitado de las excepciones. Por eso no se actualizaba la documentación.
